/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/app/game/game.module';
import * as i2 from './game.component.ngfactory';
import * as i3 from './games-view.component.ngfactory';
import * as i4 from '@angular/common';
import * as i5 from '@angular/http';
import * as i6 from '@angular/forms';
import * as i7 from '@angular/router';
import * as i8 from '../../../../src/app/game/game-routing.module';
import * as i9 from '../../../../src/app/game/game.component';
import * as i10 from '../../../../src/app/game/games-view.component';
export const GameModuleNgFactory:i0.NgModuleFactory<i1.GameModule> = i0.ɵcmf(i1.GameModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.GameViewComponentNgFactory,i3.GamesViewComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i4.NgLocalization,i4.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(4608,i5.BrowserXhr,i5.BrowserXhr,([] as any[])),
          i0.ɵmpd(4608,i5.ResponseOptions,i5.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,
              i5.XSRFStrategy,i5.ɵb,([] as any[])),i0.ɵmpd(4608,i5.XHRBackend,i5.XHRBackend,
              [i5.BrowserXhr,i5.ResponseOptions,i5.XSRFStrategy]),i0.ɵmpd(4608,i5.RequestOptions,
              i5.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,i5.Http,i5.ɵc,[i5.XHRBackend,
              i5.RequestOptions]),i0.ɵmpd(4608,i6.ɵi,i6.ɵi,([] as any[])),i0.ɵmpd(512,
              i4.CommonModule,i4.CommonModule,([] as any[])),i0.ɵmpd(512,i5.HttpModule,
              i5.HttpModule,([] as any[])),i0.ɵmpd(512,i6.ɵba,i6.ɵba,([] as any[])),
          i0.ɵmpd(512,i6.FormsModule,i6.FormsModule,([] as any[])),i0.ɵmpd(512,i7.RouterModule,
              i7.RouterModule,[[2,i7.ɵa],[2,i7.Router]]),i0.ɵmpd(512,i8.GameRoutingModule,
              i8.GameRoutingModule,([] as any[])),i0.ɵmpd(512,i1.GameModule,i1.GameModule,
              ([] as any[])),i0.ɵmpd(1024,i7.ROUTES,() => {
            return [[{path:'game/:id',component:i9.GameViewComponent},{path:'games',
                component:i10.GamesViewComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvamFtaWUvRGVza3RvcC9wbGF5L3NyYy9hcHAvZ2FtZS9nYW1lLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9qYW1pZS9EZXNrdG9wL3BsYXkvc3JjL2FwcC9nYW1lL2dhbWUubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
