/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/app/game/game-routing.module';
import * as i2 from './game.component.ngfactory';
import * as i3 from './games-view.component.ngfactory';
import * as i4 from '@angular/router';
import * as i5 from '../../../../src/app/game/game.component';
import * as i6 from '../../../../src/app/game/games-view.component';
export const GameRoutingModuleNgFactory:i0.NgModuleFactory<i1.GameRoutingModule> = i0.ɵcmf(i1.GameRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.GameViewComponentNgFactory,i3.GamesViewComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(512,i4.RouterModule,i4.RouterModule,[[2,i4.ɵa],
          [2,i4.Router]]),i0.ɵmpd(512,i1.GameRoutingModule,i1.GameRoutingModule,([] as any[])),
          i0.ɵmpd(1024,i4.ROUTES,() => {
            return [[{path:'game/:id',component:i5.GameViewComponent},{path:'games',
                component:i6.GamesViewComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvamFtaWUvRGVza3RvcC9wbGF5L3NyYy9hcHAvZ2FtZS9nYW1lLXJvdXRpbmcubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2phbWllL0Rlc2t0b3AvcGxheS9zcmMvYXBwL2dhbWUvZ2FtZS1yb3V0aW5nLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
