/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../game/game-list.component.ngfactory';
import * as i2 from '../../../../src/app/game/game-list.component';
import * as i3 from '@angular/router';
import * as i4 from '../../../../src/app/game/game.service';
import * as i5 from '../../../../src/app/user/member-home.component';
const styles_MemberHomeComponent:any[] = ([] as any[]);
export const RenderType_MemberHomeComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_MemberHomeComponent,data:{}});
export function View_MemberHomeComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),19,'div',[['class',
      'container']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n\n	'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          16,'div',[['class','row']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['\n		'])),(_l()(),i0.ɵeld(0,
          (null as any),(null as any),7,'div',[['class','col-md-3']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['\n			'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['',''])),(_l()(),i0.ɵted((null as any),['\n			'])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['Total Games:'])),(_l()(),i0.ɵted((null as any),['\n		'])),(_l()(),i0.ɵted((null as any),
          ['\n		'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),4,'div',[['class',
          'col-md-9']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n			'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'game-list',([] as any[]),(null as any),(null as any),(null as any),i1.View_GameListComponent_0,
          i1.RenderType_GameListComponent)),i0.ɵdid(114688,(null as any),0,i2.GameListComponent,
          [i3.ActivatedRoute,i4.GameService,i3.Router],(null as any),(null as any)),
      (_l()(),i0.ɵted((null as any),['\n		'])),(_l()(),i0.ɵted((null as any),['\n	'])),
      (_l()(),i0.ɵted((null as any),['\n\n\n']))],(_ck,_v) => {
    _ck(_v,16,0);
  },(_ck,_v) => {
    var _co:i5.MemberHomeComponent = _v.component;
    const currVal_0:any = _co.user.username;
    _ck(_v,7,0,currVal_0);
  });
}
export function View_MemberHomeComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'member-home',
      ([] as any[]),(null as any),(null as any),(null as any),View_MemberHomeComponent_0,
      RenderType_MemberHomeComponent)),i0.ɵdid(114688,(null as any),0,i5.MemberHomeComponent,
      [i4.GameService,i3.Router],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const MemberHomeComponentNgFactory:i0.ComponentFactory<i5.MemberHomeComponent> = i0.ɵccf('member-home',
    i5.MemberHomeComponent,View_MemberHomeComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvamFtaWUvRGVza3RvcC9wbGF5L3NyYy9hcHAvdXNlci9tZW1iZXItaG9tZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvamFtaWUvRGVza3RvcC9wbGF5L3NyYy9hcHAvdXNlci9tZW1iZXItaG9tZS5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9qYW1pZS9EZXNrdG9wL3BsYXkvc3JjL2FwcC91c2VyL21lbWJlci1ob21lLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvamFtaWUvRGVza3RvcC9wbGF5L3NyYy9hcHAvdXNlci9tZW1iZXItaG9tZS5jb21wb25lbnQudHMuTWVtYmVySG9tZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cclxuXHJcblx0PGRpdiBjbGFzcz1cInJvd1wiPlxyXG5cdFx0PGRpdiBjbGFzcz1cImNvbC1tZC0zXCI+XHJcblx0XHRcdDxoMT57e3VzZXIudXNlcm5hbWV9fTwvaDE+XHJcblx0XHRcdDxwPlRvdGFsIEdhbWVzOjwvcD5cclxuXHRcdDwvZGl2PlxyXG5cdFx0PGRpdiBjbGFzcz1cImNvbC1tZC05XCI+XHJcblx0XHRcdDxnYW1lLWxpc3Q+PC9nYW1lLWxpc3Q+XHJcblx0XHQ8L2Rpdj5cclxuXHQ8L2Rpdj5cclxuXHJcblxyXG48L2Rpdj4iLCI8bWVtYmVyLWhvbWU+PC9tZW1iZXItaG9tZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUF1QiwwQ0FFdEI7VUFBQTtVQUFBLGdCQUFpQix5Q0FDaEI7VUFBQTtVQUFBLDBEQUFzQjtVQUFBLFlBQ3JCO1VBQUE7TUFBSSx3Q0FBc0I7TUFDMUI7VUFBQSwwREFBRztVQUFBLG1CQUFnQix5Q0FDZDtVQUFBLFdBQ047VUFBQTtNQUFzQiwwQ0FDckI7VUFBQTt5Q0FBQSxVQUFBO1VBQUE7TUFBdUIseUNBQ2xCO01BQ0Q7SUFGSjs7O0lBSkk7SUFBQTs7OztvQkNKUDtNQUFBO29DQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
