/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/app/user/user-routing.module';
import * as i2 from './register.component.ngfactory';
import * as i3 from './member-home.component.ngfactory';
import * as i4 from './message.component.ngfactory';
import * as i5 from './public-profile.component.ngfactory';
import * as i6 from '@angular/router';
import * as i7 from '../../../../src/app/user/register.component';
import * as i8 from '../../../../src/app/user/member-home.component';
import * as i9 from '../../../../src/app/user/message.component';
import * as i10 from '../../../../src/app/user/public-profile.component';
export const UserRoutingModuleNgFactory:i0.NgModuleFactory<i1.UserRoutingModule> = i0.ɵcmf(i1.UserRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.RegisterComponentNgFactory,i3.MemberHomeComponentNgFactory,i4.MessageViewComponentNgFactory,
              i5.PublicProfileViewComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(512,i6.RouterModule,i6.RouterModule,[[2,i6.ɵa],
          [2,i6.Router]]),i0.ɵmpd(512,i1.UserRoutingModule,i1.UserRoutingModule,([] as any[])),
          i0.ɵmpd(1024,i6.ROUTES,() => {
            return [[{path:'register',component:i7.RegisterComponent},{path:'user',
                component:i8.MemberHomeComponent},{path:'messages',component:i9.MessageViewComponent},
                {path:'user/:id',component:i10.PublicProfileViewComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvamFtaWUvRGVza3RvcC9wbGF5L3NyYy9hcHAvdXNlci91c2VyLXJvdXRpbmcubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2phbWllL0Rlc2t0b3AvcGxheS9zcmMvYXBwL3VzZXIvdXNlci1yb3V0aW5nLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
