/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/app/user/user.module';
import * as i2 from './register.component.ngfactory';
import * as i3 from './member-home.component.ngfactory';
import * as i4 from './message.component.ngfactory';
import * as i5 from './public-profile.component.ngfactory';
import * as i6 from '../game/game.component.ngfactory';
import * as i7 from '../game/games-view.component.ngfactory';
import * as i8 from '@angular/common';
import * as i9 from '@angular/http';
import * as i10 from '@angular/forms';
import * as i11 from '../../../../src/app/user/user.service';
import * as i12 from '@angular/router';
import * as i13 from '../../../../src/app/user/user-routing.module';
import * as i14 from '../../../../src/app/game/game-routing.module';
import * as i15 from '../../../../src/app/game/game.module';
import * as i16 from '../../../../src/app/user/register.component';
import * as i17 from '../../../../src/app/user/member-home.component';
import * as i18 from '../../../../src/app/user/message.component';
import * as i19 from '../../../../src/app/user/public-profile.component';
import * as i20 from '../../../../src/app/game/game.component';
import * as i21 from '../../../../src/app/game/games-view.component';
export const UserModuleNgFactory:i0.NgModuleFactory<i1.UserModule> = i0.ɵcmf(i1.UserModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.RegisterComponentNgFactory,i3.MemberHomeComponentNgFactory,i4.MessageViewComponentNgFactory,
              i5.PublicProfileViewComponentNgFactory,i6.GameViewComponentNgFactory,
              i7.GamesViewComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(4608,i8.NgLocalization,i8.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,
              i9.BrowserXhr,i9.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i9.ResponseOptions,
              i9.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,i9.XSRFStrategy,i9.ɵb,
              ([] as any[])),i0.ɵmpd(4608,i9.XHRBackend,i9.XHRBackend,[i9.BrowserXhr,
              i9.ResponseOptions,i9.XSRFStrategy]),i0.ɵmpd(4608,i9.RequestOptions,
              i9.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,i9.Http,i9.ɵc,[i9.XHRBackend,
              i9.RequestOptions]),i0.ɵmpd(4608,i10.ɵi,i10.ɵi,([] as any[])),i0.ɵmpd(4608,
              i11.UserService,i11.UserService,[i9.Http,i12.Router]),i0.ɵmpd(512,i8.CommonModule,
              i8.CommonModule,([] as any[])),i0.ɵmpd(512,i9.HttpModule,i9.HttpModule,
              ([] as any[])),i0.ɵmpd(512,i10.ɵba,i10.ɵba,([] as any[])),i0.ɵmpd(512,
              i10.FormsModule,i10.FormsModule,([] as any[])),i0.ɵmpd(512,i12.RouterModule,
              i12.RouterModule,[[2,i12.ɵa],[2,i12.Router]]),i0.ɵmpd(512,i13.UserRoutingModule,
              i13.UserRoutingModule,([] as any[])),i0.ɵmpd(512,i14.GameRoutingModule,
              i14.GameRoutingModule,([] as any[])),i0.ɵmpd(512,i15.GameModule,i15.GameModule,
              ([] as any[])),i0.ɵmpd(512,i1.UserModule,i1.UserModule,([] as any[])),
          i0.ɵmpd(1024,i12.ROUTES,() => {
            return [[{path:'register',component:i16.RegisterComponent},{path:'user',
                component:i17.MemberHomeComponent},{path:'messages',component:i18.MessageViewComponent},
                {path:'user/:id',component:i19.PublicProfileViewComponent}],[{path:'game/:id',
                component:i20.GameViewComponent},{path:'games',component:i21.GamesViewComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvamFtaWUvRGVza3RvcC9wbGF5L3NyYy9hcHAvdXNlci91c2VyLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9qYW1pZS9EZXNrdG9wL3BsYXkvc3JjL2FwcC91c2VyL3VzZXIubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
