/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './navbar.component.ngfactory';
import * as i3 from '../../../src/app/navbar.component';
import * as i4 from '@angular/router';
import * as i5 from '../../../src/app/game/game.service';
import * as i6 from '@angular/http';
import * as i7 from '../../../src/app/app.component';
import * as i8 from 'angular-oauth2-oidc/dist/src/oauth-service';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'nav-bar',([] as any[]),
      (null as any),(null as any),(null as any),i2.View_navbarComponent_0,i2.RenderType_navbarComponent)),
      i1.ɵdid(114688,(null as any),0,i3.navbarComponent,([] as any[]),(null as any),
          (null as any)),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(16777216,
          (null as any),(null as any),1,'router-outlet',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),i1.ɵdid(212992,
          (null as any),0,i4.RouterOutlet,[i4.ChildrenOutletContexts,i1.ViewContainerRef,
              i1.ComponentFactoryResolver,[8,(null as any)],i1.ChangeDetectorRef],
          (null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
    _ck(_v,4,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),2,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵprd(4608,(null as any),i5.GameService,i5.GameService,[i6.Http]),i1.ɵdid(49152,
          (null as any),0,i7.AppComponent,[i8.OAuthService],(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i7.AppComponent> = i1.ɵccf('app-root',
    i7.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvamFtaWUvRGVza3RvcC9wbGF5L3NyYy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9qYW1pZS9EZXNrdG9wL3BsYXkvc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvamFtaWUvRGVza3RvcC9wbGF5L3NyYy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvamFtaWUvRGVza3RvcC9wbGF5L3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8bmF2LWJhcj48L25hdi1iYXI+XG48cm91dGVyLW91dGxldD48L3JvdXRlci1vdXRsZXQ+IiwiPGFwcC1yb290PjwvYXBwLXJvb3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7YUFBQTtVQUFBLGVBQW1CLHVDQUNuQjtVQUFBO1VBQUEsaUVBQUE7VUFBQTswQ0FBQTtVQUFBO0lBREE7SUFDQTs7OztvQkNEQTtNQUFBO2FBQUEsb0VBQUE7VUFBQTs7OzsifQ==
