/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/app/app.module';
import * as i2 from '../../../src/app/app.component';
import * as i3 from './game/game.component.ngfactory';
import * as i4 from './game/games-view.component.ngfactory';
import * as i5 from './user/register.component.ngfactory';
import * as i6 from './user/member-home.component.ngfactory';
import * as i7 from './user/message.component.ngfactory';
import * as i8 from './user/public-profile.component.ngfactory';
import * as i9 from './home.component.ngfactory';
import * as i10 from './about.component.ngfactory';
import * as i11 from './page-not-found.component.ngfactory';
import * as i12 from './app.component.ngfactory';
import * as i13 from '@angular/common';
import * as i14 from '@angular/platform-browser';
import * as i15 from '@angular/http';
import * as i16 from '@angular/forms';
import * as i17 from '../../../src/app/user/user.service';
import * as i18 from '@angular/router';
import * as i19 from 'angular-oauth2-oidc/dist/src/oauth-service';
import * as i20 from 'ngx-dropdown/index';
import * as i21 from '../../../src/app/game/game.component';
import * as i22 from '../../../src/app/game/games-view.component';
import * as i23 from '../../../src/app/user/register.component';
import * as i24 from '../../../src/app/user/member-home.component';
import * as i25 from '../../../src/app/user/message.component';
import * as i26 from '../../../src/app/user/public-profile.component';
import * as i27 from '../../../src/app/home.component';
import * as i28 from '../../../src/app/about.component';
import * as i29 from '../../../src/app/page-not-found.component';
import * as i30 from '../../../src/app/game/game-routing.module';
import * as i31 from '../../../src/app/game/game.module';
import * as i32 from '../../../src/app/user/user-routing.module';
import * as i33 from '../../../src/app/user/user.module';
import * as i34 from 'angular-oauth2-oidc/dist/index';
import * as i35 from '../../../src/app/app-routing.module';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.GameViewComponentNgFactory,i4.GamesViewComponentNgFactory,i5.RegisterComponentNgFactory,
              i6.MemberHomeComponentNgFactory,i7.MessageViewComponentNgFactory,i8.PublicProfileViewComponentNgFactory,
              i9.HomePageComponentNgFactory,i10.AboutViewComponentNgFactory,i11.PageNotFoundComponentNgFactory,
              i12.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i13.NgLocalization,
              i13.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,
              ([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),
          i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),i0.ɵmpd(4608,i14.DomSanitizer,
              i14.ɵe,[i13.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i14.DomSanitizer]),
          i0.ɵmpd(4608,i14.HAMMER_GESTURE_CONFIG,i14.HammerGestureConfig,([] as any[])),
          i0.ɵmpd(5120,i14.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
            return [new i14.ɵDomEventsPlugin(p0_0),new i14.ɵKeyEventsPlugin(p1_0),
                new i14.ɵHammerGesturesPlugin(p2_0,p2_1)];
          },[i13.DOCUMENT,i13.DOCUMENT,i13.DOCUMENT,i14.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i14.EventManager,i14.EventManager,[i14.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i14.ɵDomSharedStylesHost,i14.ɵDomSharedStylesHost,[i13.DOCUMENT]),
          i0.ɵmpd(4608,i14.ɵDomRendererFactory2,i14.ɵDomRendererFactory2,[i14.EventManager,
              i14.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,(null as any),
              [i14.ɵDomRendererFactory2]),i0.ɵmpd(6144,i14.ɵSharedStylesHost,(null as any),
              [i14.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,i0.Testability,
              [i0.NgZone]),i0.ɵmpd(4608,i14.Meta,i14.Meta,[i13.DOCUMENT]),i0.ɵmpd(4608,
              i14.Title,i14.Title,[i13.DOCUMENT]),i0.ɵmpd(4608,i15.BrowserXhr,i15.BrowserXhr,
              ([] as any[])),i0.ɵmpd(4608,i15.ResponseOptions,i15.BaseResponseOptions,
              ([] as any[])),i0.ɵmpd(5120,i15.XSRFStrategy,i15.ɵb,([] as any[])),i0.ɵmpd(4608,
              i15.XHRBackend,i15.XHRBackend,[i15.BrowserXhr,i15.ResponseOptions,i15.XSRFStrategy]),
          i0.ɵmpd(4608,i15.RequestOptions,i15.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i15.Http,i15.ɵc,[i15.XHRBackend,i15.RequestOptions]),i0.ɵmpd(4608,i16.ɵi,
              i16.ɵi,([] as any[])),i0.ɵmpd(4608,i17.UserService,i17.UserService,[i15.Http,
              i18.Router]),i0.ɵmpd(5120,i18.ActivatedRoute,i18.ɵf,[i18.Router]),i0.ɵmpd(4608,
              i18.NoPreloading,i18.NoPreloading,([] as any[])),i0.ɵmpd(6144,i18.PreloadingStrategy,
              (null as any),[i18.NoPreloading]),i0.ɵmpd(135680,i18.RouterPreloader,
              i18.RouterPreloader,[i18.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i18.PreloadingStrategy]),i0.ɵmpd(4608,i18.PreloadAllModules,
              i18.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i18.ROUTER_INITIALIZER,
              i18.ɵi,[i18.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i18.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i19.OAuthService,i19.OAuthService,
              [i15.Http]),i0.ɵmpd(512,i13.CommonModule,i13.CommonModule,([] as any[])),
          i0.ɵmpd(1024,i0.ErrorHandler,i14.ɵa,([] as any[])),i0.ɵmpd(1024,i0.NgProbeToken,
              () => {
                return [i18.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i18.ɵg,i18.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i14.ɵc(p0_0,p0_1),i18.ɵh(p1_0)];
              },[[2,i14.NgProbeToken],[2,i0.NgProbeToken],i18.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i14.BrowserModule,i14.BrowserModule,[[3,i14.BrowserModule]]),
          i0.ɵmpd(512,i20.DropdownModule,i20.DropdownModule,([] as any[])),i0.ɵmpd(512,
              i15.HttpModule,i15.HttpModule,([] as any[])),i0.ɵmpd(512,i16.ɵba,i16.ɵba,
              ([] as any[])),i0.ɵmpd(512,i16.FormsModule,i16.FormsModule,([] as any[])),
          i0.ɵmpd(1024,i18.ɵa,i18.ɵd,[[3,i18.Router]]),i0.ɵmpd(512,i18.UrlSerializer,
              i18.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,i18.ChildrenOutletContexts,
              i18.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,i18.ROUTER_CONFIGURATION,
              {enableTracing:false},([] as any[])),i0.ɵmpd(1024,i13.LocationStrategy,
              i18.ɵc,[i13.PlatformLocation,[2,i13.APP_BASE_HREF],i18.ROUTER_CONFIGURATION]),
          i0.ɵmpd(512,i13.Location,i13.Location,[i13.LocationStrategy]),i0.ɵmpd(512,
              i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i18.ROUTES,() => {
            return [[{path:'game/:id',component:i21.GameViewComponent},{path:'games',
                component:i22.GamesViewComponent}],[{path:'register',component:i23.RegisterComponent},
                {path:'user',component:i24.MemberHomeComponent},{path:'messages',component:i25.MessageViewComponent},
                {path:'user/:id',component:i26.PublicProfileViewComponent}],[{path:'game/:id',
                component:i21.GameViewComponent},{path:'games',component:i22.GamesViewComponent}],
                [{path:'',component:i27.HomePageComponent},{path:'about',component:i28.AboutViewComponent},
                    {path:'**',component:i29.PageNotFoundComponent}]];
          },([] as any[])),i0.ɵmpd(1024,i18.Router,i18.ɵe,[i0.ApplicationRef,i18.UrlSerializer,
              i18.ChildrenOutletContexts,i13.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i18.ROUTES,i18.ROUTER_CONFIGURATION,[2,i18.UrlHandlingStrategy],
              [2,i18.RouteReuseStrategy]]),i0.ɵmpd(512,i18.RouterModule,i18.RouterModule,
              [[2,i18.ɵa],[2,i18.Router]]),i0.ɵmpd(512,i30.GameRoutingModule,i30.GameRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i31.GameModule,i31.GameModule,([] as any[])),
          i0.ɵmpd(512,i32.UserRoutingModule,i32.UserRoutingModule,([] as any[])),i0.ɵmpd(512,
              i33.UserModule,i33.UserModule,([] as any[])),i0.ɵmpd(512,i34.OAuthModule,
              i34.OAuthModule,([] as any[])),i0.ɵmpd(512,i35.AppRoutingModule,i35.AppRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvamFtaWUvRGVza3RvcC9wbGF5L3NyYy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9qYW1pZS9EZXNrdG9wL3BsYXkvc3JjL2FwcC9hcHAubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
