/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/app/page-not-found.component';
const styles_PageNotFoundComponent:any[] = ([] as any[]);
export const RenderType_PageNotFoundComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_PageNotFoundComponent,data:{}});
export function View_PageNotFoundComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['PAGE NOT FOUND!!!!']))],(null as any),(null as any));
}
export function View_PageNotFoundComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'page-not-found',
      ([] as any[]),(null as any),(null as any),(null as any),View_PageNotFoundComponent_0,
      RenderType_PageNotFoundComponent)),i0.ɵdid(49152,(null as any),0,i1.PageNotFoundComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const PageNotFoundComponentNgFactory:i0.ComponentFactory<i1.PageNotFoundComponent> = i0.ɵccf('page-not-found',
    i1.PageNotFoundComponent,View_PageNotFoundComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvamFtaWUvRGVza3RvcC9wbGF5L3NyYy9hcHAvcGFnZS1ub3QtZm91bmQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2phbWllL0Rlc2t0b3AvcGxheS9zcmMvYXBwL3BhZ2Utbm90LWZvdW5kLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL2phbWllL0Rlc2t0b3AvcGxheS9zcmMvYXBwL3BhZ2Utbm90LWZvdW5kLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvamFtaWUvRGVza3RvcC9wbGF5L3NyYy9hcHAvcGFnZS1ub3QtZm91bmQuY29tcG9uZW50LnRzLlBhZ2VOb3RGb3VuZENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT5QQUdFIE5PVCBGT1VORCEhISE8L2gxPiIsIjxwYWdlLW5vdC1mb3VuZD48L3BhZ2Utbm90LWZvdW5kPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUk7YUFBQTs7O29CQ0FKO01BQUE7c0NBQUEsVUFBQTtNQUFBOzs7In0=
